#!/bin/bash
# PATCH DE MISE A JOUR DE CAKEBOX
# Par Mardambey (iam.mardambey@gmail.com)
# heycakebox.com
# ./patch_maj dossier_père_de_cakebox (/var/www par défaut)

if [ $# -ne 1 ]
then
	dir="/var/www"
else
	dir=$1;
fi

cd $dir
( (
pwd

# Télécharge la nouvelle version
git clone git://github.com/MardamBeyK/Cakebox.git

# Met à jour les fichiers racines
find Cakebox/ -maxdepth 1 -type f -exec mv -v -f {} cakebox/ \;

# Met à jour les fichiers de ressources
find Cakebox/ressources/ -type f -exec mv -v -f {} cakebox/ressources/ \;

# Met à jour les fichiers d'includes
find Cakebox/inc/ -type f -exec mv -v -f {} cakebox/inc/ \;

# Supprime les fichiers temporaires
rm -R Cakebox/

# Supprime les softwares useless
rm -R cakebox/softwares

# Chmod du patch pour la prochaine MAJ
chmod +x cakebox/scripts/patch_update

# All right, bitch !
echo "Update : OK"
) 2>&1) | tee cakebox/last_update.log
